apiVersion: v1
kind: Service
metadata:
  name: redis-leader
  namespace: Guestbook
spec:
  selector:
    app: redis-leader
  ports:
  - port: 6379
    targetPort: 6379

---
apiVersion: v1
kind: Service
metadata:
  name: redis-follower
  namespace: Guestbook
spec:
  selector:
    app: redis-follower
  ports:
  - port: 6379
    targetPort: 6379