apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-leader
  namespace: Guestbook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-leader
  template:
    metadata:
      labels:
        app: redis-leader
    spec:
      containers:
      - name: redis-leader
        image: mcp/redis
        ports:
        - containerPort: 6379
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-follower
  namespace: Guestbook
spec:
  replicas: 2
  selector:
    matchLabels:
      app: redis-follower
  template:
    metadata:
      labels:
        app: redis-follower
    spec:
      containers:
      - name: redis-follower
        image: mcp/redis
        ports:
        - containerPort: 6379
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"